[package]
name = "cat-gui"
version = "0.0.5"
edition = "2024"
license = "GPL-3.0"

[lib]
name = "cat_gui"
path = "src/lib.rs"

[[bin]]
name = "cat"
path = "src/main.rs"

[dependencies]
cat-core = { path = "../core" }
eframe = { version = "0.36.1", default-features = false, features = ["glow", "default_fonts", "persistence"] }
winit = "0.30"
wry = { version = "0.56.1", default-features = false, features = ["os-webview"] }

[build-dependencies]
winresource = "0.1.31"
